### PR TITLE
Updated to .Net 4.6.2, xunit 2.2.0 and NBench 1.0.4

### PR DESCRIPTION
**Pull request by andreyleskov**
Hi there! 
Using Pro.NBench.xUnit in my project. Thank you for great stuff! 
Just updated packages & .net version to be aligned to latest akka packages.

### CODE REVIEW

**Comment by mcquiggd** [comment]
@andreyleskov 

Hi Andrey,

glad you are finding this useful - and thanks for the pull request. Merged, currently testing... then I will update the NuGet packages.

David

**Comment by andreyleskov** [comment]
Hi, David!
I'm using my fork now, but will gladly switch to your official package )
Hope tests will be fine.

2017-07-28 17:48 GMT+03:00 David Paul McQuiggin <notifications@github.com>:

**Comment by mcquiggd** [comment]
I should be able to release it to the NuGet Repository this weekend.

Feature requests / contributions are welcome...

**Comment by mcquiggd** [comment]
@andreyleskov 

Hi Andrey,

 firstly thanks for your input - I checked the code from the Pull Request, and noticed the projects were still targeting `NET461`, although the packages installed were specified as targeting `NET462`. They do not actually _require_ this version. And in fact the dependencies were set to allow working with earlier versions of the packages, while still supporting later ones if the user decided to install them.

At the moment I have changed the target framework back down to be `NET452` (the lowest supported by NBench 1.0.4), to give the widest coverage of potential usage - I have tested this change, and this functions correctly with the latest versions of `NBench `and `XUnit`, and will also provide compatibility with any .Net Framework 4.5.2+. This code is checked in, all tests passing.

**A question:**

Was there a particular reason why you needed the package to target a later version of the .Net framework for your usage? Were you experiencing errors?

I won't revert the Pull Request, as it does make sense to update to the latest released `xunit `and `NBench`.

Also, this week I will look to port `Pro.NBench.xUnit `to `NetStandard`, possibly 1.6 if all is compatible, to open this up for use with .Net Core. Perhaps you would like to get involved / test this with me?

**Comment by mcquiggd** [comment]
Ok, version 1.0.3 published, supporting .Net 4.5.2+.

**Comment by andreyleskov** [comment]
Hi, David!
Thank you for careful testing and keeping .net version as low as possible
for compability.
Motivation for the upgrade was incorrect work of NBench.XUnit with akka
1.1.3 and latest xunit.

2017-07-31 20:26 GMT+03:00 David Paul McQuiggin <notifications@github.com>:

**Comment by mcquiggd** [comment]
@andreyleskov 

Ok ... it should have been possible to just update the `NBench `and `xUnit` NuGet packages in your project to the later versions - no code changes were made to `Pro.NBench.xUnit` when I successfully tested it with the latest versions, and it did not specify an exact version of it's dependencies.

But anyway, version `1.0.3` is published, and has a dependency on the latest version (or subsequently released versions) of `NBench `and `xUnit`, so they will be automatically installed when adding  `Pro.NBench.xUnit` to a new project. 

I also create Releases on GitHub which include the NuGet packages, so people can also download previous versions in case of problems.

Next task - .Net Core support...

**Pull request merged**
